name: fl_utilities
description:
  Simple Flutter utilities such as [BuildContext] shorthands extension,
  `debounce` extension on [ValueChanged], and more.
version: 3.0.0
repository: https://github.com/KeidsID/fl_utilities
documentation: https://docs.page/KeidsID/fl_utilities

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # gitlint
  commitlint_cli: ^0.8.1
  danger_core: ^2.0.0
  husky: ^0.1.7
