name: 💡 Feature Request
description: Request a new feature
title: "feat: "
labels: ["feat"]
assignees: ["KeidsID"]
body:
  - id: description
    type: textarea
    attributes:
      label: What feature?
      placeholder: What feature do you want to add?
    validations:
      required: true
  - id: additional-media
    type: textarea
    attributes:
      label: Additional Images/Videos
      placeholder: Provide screenshots or videos that may help showcase the feature
