name: widgets
description: fl_utilities widgets example
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  fl_utilities:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
