name: Upload Coverage

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download coverage
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: test.yml
          name: test-coverage
          path: ./coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: KeidsID/fl_utilities
